name: Build Godot Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Blender
        uses: Moguri/setup-blender@v1
        with:
          blender-version: '4.4'

      - name: Godot Setup
        uses: Vitorgus/Setup-Godot@v1.1.1
        with:
          godot-version:  3.5.1-stable
          mono: false
          download-templates: true
      
      - name: Build Godot (Debug)
        uses: yeslayla/build-godot-action@v1.4.1
        with:
          name: game-debug
          preset: 'Windows Desktop'
          package: true
          debugMode: true
          projectDir: .

      - name: Upload Debug Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-debug
          path: game-debug.zip
          retention-days: 7

      - name: Build Godot (Release)
        uses: yeslayla/build-godot-action@v1.4.1
        with:
          name: game-release
          preset: 'Windows Desktop'
          package: true
          debugMode: false
          projectDir: .

      - name: Upload Release Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-release
          path: game-release.zip
          retention-days: 7
