name: Build Godot Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Blender
        uses: Moguri/setup-blender@v1
        with:
          blender-version: '4.4'

      - name: Install Godot
        shell: bash
        run: |
          INSTALL_DIR=${HOME}/.godot-install-dir/3.5.1-stable
          mkdir -p $INSTALL_DIR

          echo "Creating $INSTALL_DIR"

          GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/3.5.1-stable/Godot_v3.5.1-stable_linux_headless.64.zip

          echo "Downloading: $GODOT_DOWNLOAD_URL"

          cd $INSTALL_DIR
          wget -O godot.zip -q $GODOT_DOWNLOAD_URL
          unzip godot.zip
          rm -rf godot.zip

          mv Godot_v3.5.1-stable_linux_headless.64 godot

          ls -la $INSTALL_DIR
          echo $INSTALL_DIR >> $GITHUB_PATH

      - name: Download Export Templates
        shell: bash
        run: |
          cd $RUNNER_TEMP

          wget -O templates.tpz -q https://github.com/godotengine/godot-builds/releases/download/3.5.1-stable/Godot_v3.5.1-stable_export_templates.tpz
          EXPORT_TEMPLATES_DIR=${HOME}/.local/share/godot/export_templates/3.5.1.stable

          unzip templates.tpz
          rm -rf templates.tpz

          mkdir -p $EXPORT_TEMPLATES_DIR
          mv ./templates/* $EXPORT_TEMPLATES_DIR
          ls -la $EXPORT_TEMPLATES_DIR

      - name: Import Project Assets
        shell: bash
        run: |
          timeout 150 godot --editor --path .
          echo "Project imported successfully"

      - name: Build Godot (Debug)
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          godot --headless --path . --export-debug "Windows Desktop" build/Windows/debug/game.exe
          cd build/Windows/debug
          zip -r game-debug.zip ./*
          mv game-debug.zip $GITHUB_WORKSPACE/

      - name: Upload Debug Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-debug
          path: game-debug.zip
          retention-days: 7

      - name: Build Godot (Release)
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          godot --headless --path . --export "Windows Desktop" build/Windows/release/game.exe
          cd build/Windows/release
          zip -r game-release.zip ./*
          mv game-release.zip $GITHUB_WORKSPACE/

      - name: Upload Release Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-release
          path: game-release.zip
          retention-days: 7
